// Model encodings extracted from models_sample folder
export const MODEL_ENCODINGS = {
  cl100k_base: [
    "babbage-002",
    "davinci-002",
    "gpt-3.5",
    "gpt-3.5-turbo",
    "gpt-3.5-turbo-instruct",
    "gpt-4",
    "gpt-4-turbo",
    "text-embedding-3-large",
    "text-embedding-3-small",
    "text-embedding-ada-002",
  ],
  o200k_base: [
    "chatgpt-4o-latest",
    "codex-mini-latest",
    "computer-use-preview",
    "dall-e-2",
    "dall-e-3",
    "gpt-4.1",
    "gpt-4.1-mini",
    "gpt-4.1-nano",
    "gpt-4.5-preview",
    "gpt-4o",
    "gpt-4o-audio-preview",
    "gpt-4o-mini",
    "gpt-4o-mini-audio-preview",
    "gpt-4o-mini-realtime-preview",
    "gpt-4o-mini-search-preview",
    "gpt-4o-mini-transcribe",
    "gpt-4o-mini-tts",
    "gpt-4o-realtime-preview",
    "gpt-4o-search-preview",
    "gpt-4o-transcribe",
    "gpt-5",
    "gpt-5-chat-latest",
    "gpt-5-codex",
    "gpt-5-mini",
    "gpt-5-nano",
    "gpt-5-pro",
    "gpt-audio",
    "gpt-audio-mini",
    "gpt-image-1",
    "gpt-image-1-mini",
    "gpt-realtime",
    "gpt-realtime-mini",
    "o1",
    "o1-mini",
    "o1-preview",
    "o1-pro",
    "o3",
    "o3-deep-research",
    "o3-mini",
    "o3-pro",
    "o4-mini",
    "o4-mini-deep-research",
    "omni-moderation-latest",
    "sora-2",
    "sora-2-pro",
    "text-moderation-latest",
    "tts-1",
    "tts-1-hd",
    "whisper-1",
  ],
  o200k_harmony: ["gpt-oss-120b", "gpt-oss-20b"],
  p50k_base: [
    "code-cushman-001",
    "code-cushman-002",
    "code-davinci-001",
    "code-davinci-002",
    "cushman-codex",
    "davinci-codex",
    "text-davinci-002",
    "text-davinci-003",
  ],
  p50k_edit: ["code-davinci-edit-001", "text-davinci-edit-001"],
  r50k_base: [
    "ada",
    "babbage",
    "code-search-ada-code-001",
    "code-search-ada-text-001",
    "code-search-babbage-code-001",
    "code-search-babbage-text-001",
    "curie",
    "davinci",
    "text-ada-001",
    "text-babbage-001",
    "text-curie-001",
    "text-davinci-001",
    "text-search-ada-doc-001",
    "text-search-ada-query-001",
    "text-search-babbage-doc-001",
    "text-search-babbage-query-001",
    "text-search-curie-doc-001",
    "text-search-curie-query-001",
    "text-search-davinci-doc-001",
    "text-search-davinci-query-001",
    "text-similarity-ada-001",
    "text-similarity-babbage-001",
    "text-similarity-curie-001",
    "text-similarity-davinci-001",
  ],
} as const;

// Export type for TypeScript
export type EncodingType =
  | "o200k_base"
  | "cl100k_base"
  | "p50k_base"
  | "p50k_edit"
  | "r50k_base"
  | "o200k_harmony";
export type ModelName = (typeof MODEL_ENCODINGS)[EncodingType][number];

// Model display names mapping
export const MODEL_DISPLAY_NAMES: Record<string, string> = {
  "babbage-002": "Babbage 002",
  "davinci-002": "Davinci 002",
  "gpt-3.5": "GPT 3.5",
  "gpt-3.5-turbo": "GPT 3.5 Turbo",
  "gpt-3.5-turbo-instruct": "GPT 3.5 Turbo Instruct",
  "gpt-4": "GPT 4",
  "gpt-4-turbo": "GPT 4 Turbo",
  "text-embedding-3-large": "Text Embedding 3 Large",
  "text-embedding-3-small": "Text Embedding 3 Small",
  "text-embedding-ada-002": "Text Embedding Ada 002",
  "chatgpt-4o-latest": "ChatGPT-4o Latest",
  "codex-mini-latest": "Codex Mini Latest",
  "computer-use-preview": "Computer Use Preview",
  "dall-e-2": "DALL-E 2",
  "dall-e-3": "DALL-E 3",
  "gpt-4.1": "GPT 4.1",
  "gpt-4.1-mini": "GPT 4.1 Mini",
  "gpt-4.1-nano": "GPT 4.1 Nano",
  "gpt-4.5-preview": "GPT 4.5 Preview",
  "gpt-4o": "GPT-4o",
  "gpt-4o-audio-preview": "GPT-4o Audio Preview",
  "gpt-4o-mini": "GPT-4o Mini",
  "gpt-4o-mini-audio-preview": "GPT-4o Mini Audio Preview",
  "gpt-4o-mini-audio-preview-2024-12-17":
    "GPT-4o Mini Audio Preview 2024-12-17",
  "gpt-4o-mini-realtime-preview": "GPT-4o Mini Realtime Preview",
  "gpt-4o-mini-search-preview": "GPT-4o Mini Search Preview",
  "gpt-4o-mini-transcribe": "GPT-4o Mini Transcribe",
  "gpt-4o-mini-tts": "GPT-4o Mini TTS",
  "gpt-4o-realtime-preview": "GPT-4o Realtime Preview",
  "gpt-4o-search-preview": "GPT-4o Search Preview",
  "gpt-4o-transcribe": "GPT-4o Transcribe",
  "gpt-5": "GPT-5",
  "gpt-5-chat-latest": "GPT-5 Chat Latest",
  "gpt-5-codex": "GPT-5 Codex",
  "gpt-5-mini": "GPT-5 Mini",
  "gpt-5-nano": "GPT-5 Nano",
  "gpt-5-pro": "GPT-5 Pro",
  "gpt-audio": "GPT Audio",
  "gpt-audio-mini": "GPT Audio Mini",
  "gpt-image-1": "GPT Image 1",
  "gpt-image-1-mini": "GPT Image 1 Mini",
  "gpt-realtime": "GPT Realtime",
  "gpt-realtime-mini": "GPT Realtime Mini",
  o1: "O1",
  "o1-mini": "O1 Mini",
  "o1-preview": "O1 Preview",
  "o1-pro": "O1 Pro",
  o3: "O3",
  "o3-deep-research": "O3 Deep Research",
  "o3-mini": "O3 Mini",
  "o3-pro": "O3 Pro",
  "o4-mini": "O4 Mini",
  "o4-mini-deep-research": "O4 Mini Deep Research",
  "omni-moderation-latest": "Omni Moderation Latest",
  "sora-2": "Sora 2",
  "sora-2-pro": "Sora 2 Pro",
  "text-moderation-007": "Text Moderation 007",
  "text-moderation-latest": "Text Moderation Latest",
  "text-moderation-stable": "Text Moderation Stable",
  "tts-1": "TTS-1",
  "tts-1-hd": "TTS-1 HD",
  "whisper-1": "Whisper 1",
  "gpt-oss-120b": "GPT-OSS 120B",
  "gpt-oss-20b": "GPT-OSS 20B",
  "code-cushman-001": "Code Cushman 001",
  "code-cushman-002": "Code Cushman 002",
  "code-davinci-001": "Code Davinci 001",
  "code-davinci-002": "Code Davinci 002",
  "cushman-codex": "Cushman Codex",
  "davinci-codex": "Davinci Codex",
  "text-davinci-002": "Text Davinci 002",
  "text-davinci-003": "Text Davinci 003",
  "code-davinci-edit-001": "Code Davinci Edit 001",
  "text-davinci-edit-001": "Text Davinci Edit 001",
  ada: "Ada",
  babbage: "Babbage",
  "code-search-ada-code-001": "Code Search Ada Code 001",
  "code-search-ada-text-001": "Code Search Ada Text 001",
  "code-search-babbage-code-001": "Code Search Babbage Code 001",
  "code-search-babbage-text-001": "Code Search Babbage Text 001",
  curie: "Curie",
  davinci: "Davinci",
  "text-ada-001": "Text Ada 001",
  "text-babbage-001": "Text Babbage 001",
  "text-curie-001": "Text Curie 001",
  "text-davinci-001": "Text Davinci 001",
  "text-search-ada-doc-001": "Text Search Ada Doc 001",
  "text-search-ada-query-001": "Text Search Ada Query 001",
  "text-search-babbage-doc-001": "Text Search Babbage Doc 001",
  "text-search-babbage-query-001": "Text Search Babbage Query 001",
  "text-search-curie-doc-001": "Text Search Curie Doc 001",
  "text-search-curie-query-001": "Text Search Curie Query 001",
  "text-search-davinci-doc-001": "Text Search Davinci Doc 001",
  "text-search-davinci-query-001": "Text Search Davinci Query 001",
  "text-similarity-ada-001": "Text Similarity Ada 001",
  "text-similarity-babbage-001": "Text Similarity Babbage 001",
  "text-similarity-curie-001": "Text Similarity Curie 001",
  "text-similarity-davinci-001": "Text Similarity Davinci 001",
};

// Function to check if a string is an encoding type
export function isEncodingType(value: string): value is EncodingType {
  return value in MODEL_ENCODINGS;
}

// Function to get encoding for a specific model
export function getEncodingForModel(modelName: string): EncodingType {
  for (const [encoding, models] of Object.entries(MODEL_ENCODINGS)) {
    if (models.includes(modelName as never)) {
      return encoding as EncodingType;
    }
  }
  return "o200k_base"; // Default fallback
}
